name: Build

on:
  schedule:
    - cron: "0 10 * * *" # everyday at 10am

  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]
  
  push:
    branches-ignore:
      - master
    paths-ignore:
      - README.md
      - CHANGELOG.md  # Should never be edited anyway
      - .gitignore
      - .github/**
      - Jenkinsfile

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - uses: actions/setup-dotnet@v3.2.0
        with:
          # need at least .NET 6 to build
          dotnet-version: '6.0.400'
          include-prerelease: true
      - uses: actions/setup-dotnet@v3.2.0
        with:
          # need at least .NET 7 to build
          dotnet-version: '7.0.401'
          include-prerelease: true

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.x
          include-prerelease: true

      - name: Cache Tools
        uses: actions/cache@v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('build.cake') }}

      - name: Build project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: build.cake
          target: SonarEnd
          verbosity: Diagnostic
          cake-version: 3.1.0
          arguments: |
            token: ${{ secrets.SONAR_TOKEN }}
            mode: CI
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: | 
            artifact
            tests/Cake.DependencyTrack.EndToEnd.Tests/docker/docker-compose.yml
  
  
  
  end-to-end-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: artifact
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "artifact/docker-compose.yml"
      - name: Make test call
        run: curl -X GET http://localhost:8081/api/version
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifact
      - name: Build project
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: build.cake
          verbosity: Diagnostic
          cake-version: 3.1.0