name: Build

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
        
      - uses: actions/setup-dotnet@v3.2.0
        with:
          # need at least .NET 6 to build
          dotnet-version: '6.0.400'
          include-prerelease: true
      - uses: actions/setup-dotnet@v3.2.0
        with:
          # need at least .NET 7 to build
          dotnet-version: '7.0.401'
          include-prerelease: true

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.1.818
          include-prerelease: true

      - name: Cache Tools
        uses: actions/cache@v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('build.cake') }}

      - name: Build project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: build.cake
          target: SonarEnd
          verbosity: Diagnostic
          cake-version: 3.1.0
          arguments: |
            token: ${{ secrets.SONAR_TOKEN }}

      - name: Create Test Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        if: runner.os == 'Linux'
        with:
          label: Test Coverage
          color: orange
          path: tests/Cake.DependencyTrack.Tests/TestResults/coverage.net6.0.opencover.xml
          gist-filename: cakedependancytrackcoverage.json
          gist-id: cb35602c6a5e75e8a32ca62e0d79631b
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}

      - name: Print code coverage
        if: runner.os == 'Linux'
        run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"

      - name: Print badge data
        if: runner.os == 'Linux'
        run: echo "Badge data ${{steps.test_step.outputs.badge}}"      