name: DtrackContractCheck
on:
  schedule:
    - cron: "0 1 * * 1"
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]

  push:
    branches-ignore:
      - master
jobs:
  contract-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: ./tests/Cake.DependencyTrack.Contract.Tests/docker-compose.yml
      - name: Make test call
        run: curl -X GET http://localhost:8081/api/version
